README.md, src/Riok.Mapperly.Abstractions/MapperAttribute.cs, src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilder/DirectAssignmentMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilder/ExplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilder/ImplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs, test/Riok.Mapperly.Tests/Mapping/DirectAssignmentTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs, test/Riok.Mapperly.Tests/TestSourceBuilder.cs, test/Riok.Mapperly.Tests/TestSourceBuilderOptions.cs
Add a configuration whether objects are directly assigned if possible or need to be deeply cloned
By default direct assignments are allowed
=> feat: add configuration whether to deep clone objects

docs/docs/02-configuration/01-mapper.md, src/Riok.Mapperly.Abstractions/MapperAttribute.cs, src/Riok.Mapperly.Abstractions/PropertyNameMappingStrategy.cs, src/Riok.Mapperly/Descriptors/MappingBuilder/ObjectPropertyMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs, test/Riok.Mapperly.Tests/TestSourceBuilder.cs, test/Riok.Mapperly.Tests/TestSourceBuilderOptions.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPropertyNameMappingStrategyCaseSensitive#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPropertyNameMappingStrategyCaseSensitive.verified.txt
This adds support for property naming strategy (case sensitive/insensitve).
For example:
```
[Mapper(PropertyNameMappingStrategy=PropertyNameMappingStrategy.CaseInsensitive)]
class Mapper { partial B Map(A source); }
class A { public string StringValue { get; set; } }
class B { public string stringvalue { get; set; } }
````
Using `PropertyNameMappingStrategy.CaseInsensitive` will match property `A.StringValue` with `B.stringvalue`.
PR contains 2 unit tests: `WithPropertyNameMappingStrategyCaseInsensitive` and `WithPropertyNameMappingStrategyCaseSensitive`.
Let me know if such changes can be added into main repo. Also if naming convention i use are acceptable or need some tuning.
=> Added property name mapping strategy according to issue #186

.github/workflows/release.yml
GitHub Actions deprecated set-output, replacing with github action output file.
=> chore: replace set-output with github action output file

src/Riok.Mapperly/Descriptors/Mappings/EnumNameMapping.cs, src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs, test/Riok.Mapperly.Tests/_snapshots/EnumTest.EnumToOtherEnumByNameWithoutOverlap#Mapper.g.verified.cs
=> fix: improve enum mapping runtime exception

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilder/ObjectPropertyMappingBodyBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Do not map from indexed properties and add a diagnostic instead.
Rel. https://github.com/riok/mapperly/issues/226
=> fix: do not map from indexed properties

.gitignore, docs/docs/02-configuration/07-ctor-mappings.md, src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilder/NewInstanceObjectPropertyMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilder/NewInstanceMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/Mappings/PropertyMappings/ConstructorParameterMapping.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs
Hi, thanks for this great library!
I had an issue where I tried to map a class to a record with primary constructor, where one of the property names were not matching, so I had to use the `MapProperty` attribute, this failed and I think I tracked down why. I included a couple of tests to illustrate the issue. The `ClassesCanMapToPrimaryConstructorRecordsWhenUsingMapProperty` tests failed, but it worked without `MapProperty`, so hopefully I've added the correct mapping code
=> feat: constructor mapping support for MapProperty attribute

docs/docs/02-configuration/12-analyzer-diagnostics.mdx, docs/docs/02-configuration/13-generated-source.mdx, src/Riok.Mapperly/MapperGenerator.cs
To address performance issues register output as implementation source output until #72 is addressed.
=> fix: register output as implementation source output

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectPropertyMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectPropertyMappingBodyBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyIgnoreTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.InitOnlyPropertyWithConfigurationNotFoundSourcePropertyShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.RequiredPropertySourceNotFoundShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithManualMappedNotFoundTargetPropertyShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPropertyNameMappingStrategyCaseSensitive.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithUnmatchedPropertyShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ReferenceHandlingTest.ManuallyMappedPropertiesShouldWork.verified.txt
RMG023 was also updated to include the target type, due to the way the message is invoked alongside RMG012. The message format of RMG012 was updated to follow the format of RMG020.
This relates to #68
=> fix: add target type to the RMG012 diagnostic

src/Riok.Mapperly/MapperGenerator.cs, src/Riok.Mapperly/SyntaxProvider.Roslyn4.0.cs, src/Riok.Mapperly/SyntaxProvider.Roslyn4.4.cs
`ForAttributeWithMetadataName` was added to target types with attached attributes. Should have a performance boost - (not familiar with source generators).
=> Use `ForAttributeWithMetadataName` 

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBuilders/SpecialTypeMappingBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/SpecialTypeTest.cs
Resolves #313
Resolve ide hanging/crash when object to object mapping when deep clone is enabled. I mentioned my concerns in the issue, is it correct for a simple copy to be used when deep cloning is enabled? Should I instead make this a diagnostic errror or would updating the docs and adding a note to the `UseDeepCloning` attribute be enough?
- Added another branch to `SpecialTypeMappingBuilder` for object->object edge case
- Added object->object and object?->object? tests
=> Fix crash when object to object mapping

src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/LinqConstructorMapping.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
[Resolves](https://github.com/riok/mapperly/pull/312#discussion_r1165926743)
- If target is does not exist and target is  `Queue<T>` or `Stack<T>` then use the `IEnumerable` constructors
- Uses global types
- Added 2 unit tests
=> feat: use IEnumerable constructor when possible (`Queue<T>` and `Stack<T>`)

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Closes https://github.com/riok/mapperly/issues/329
=> fix: do not diagnostic property not found if target is read only

src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachSetDictionaryExistingTargetMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/LinqDictionaryMapping.cs, src/Riok.Mapperly/Descriptors/WellKnownTypes.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDto.cs, test/Riok.Mapperly.IntegrationTests/Models/TestObject.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/MapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.RunExtensionMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/MapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.RunExtensionMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/MapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.RunExtensionMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
Resolve the last two types from #250 
- Added support for `ImmutableDictionary` and `ImmutableSortedDictionary`
- Added guards to `DictionaryMappingBuilder` to prevent existing immutable types from being assigned to in a foreach loop. - I did not copy the approach of checking for a implicit setter from the Immutable Enumerable types as this would conflict with #341.
- Added tests.
=> feat: add support for Immutable dictionaries

src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachSetDictionaryExistingTargetMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/ForEachSetDictionaryMapping.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs
Resolves #286
- Looks for an explicit setter, casting the target dictionary if one is found. - not sure if `GetExplicitIndexer` should be in `DictionaryMappingBuilder` or `ForEachSetDictionaryExistingTargetMapping`
- All casts use the global type
- Added tests
=> fix: Insert a cast to `IDictionary` when an explicit setter is present

src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacity.cs, src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs, src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityMember.cs, src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityNonEnumerated.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachAddEnumerableExistingTargetMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/ForEachAddEnumerableMapping.cs, src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.MapToExistingQueueShouldWork#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.MapToExistingStackShouldWork#Mapper.g.verified.cs
Complete #251 for enumerable types. I'm not sure how Explicit `Count` values should be treated, right now it gets the runtime type using the `is` operator. I think it should either try not to get the value or just cast the value so the explicit property can be accessed.
- Added `EnsureCapacityBuilder`, `CanEnsureCapacity` checks if ensure capacity can be used, storing the relevant information in `EnsureCapacityInfo` to be used by `TryBuildEnsureCapacityStatement` when the syntax is built.
- If both source and target have compile time sizes `TryBuildEnsureCapacityStatement` generates a simple call to `EnsureCapacity`.
- If source does not have a length/count property, `is` statements are created to check the runtime type, invoking `EnsureCapacity` with the resulting type.
- Not sure where …
=> Add ensure capacity for enumerable types.

src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachSetDictionaryExistingTargetMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/ForEachSetDictionaryMapping.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs
Resolves #251
- Modifed a bit of #312 to work with dictionaries. 
- Adjusted `ImplementsGeneric` to support interface inheritance, added a guard to `TryBuildEnsureCapacity` because `Dictionary` does have `EnsureCapacity` for older versions.
- Added 3 tests
=> fix: add `EnsureCapacity` for dictionary types

docs/docs/02-configuration/02-static-mappers.md
This is supported since https://github.com/riok/mapperly/pull/364
=> docs: rm unsupported static methods hint

src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.IntegrationTests/DeepCloningMapperTest.cs, test/Riok.Mapperly.IntegrationTests/Mapper/DeepCloningMapper.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/DeepCloningMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/DeepCloningMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/DeepCloningMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/DeepCloningMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/DeepCloningMapperTest.RunMappingShouldWork.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/DeepCloningMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/CastTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs, test/Riok.Mapperly.Tests/Mapping/SameTypeTest.cs, test/Riok.Mapperly.Tests/Mapping/SpecialTypeTest.cs
Resolves #362. `UseDeepCloning` with primitive members would work on .NET Core but failed on .NET Framework. 
Normally Mapperly generates a mapping with `DirectAssignmentMappingBuilder` when `ctx.Source.IsImmutable()` returns true. `IsImmutable` checks if the value is `IsReadonly` in .net core all primitive types are `readonly struct` whereas in .net framework they are `structs`, thus returning `IsReadonly`: `false`.
By adding an `IsUnmanaged` check, `IsUmmutable` should work on .NET Framework and will use shortcuts for user defined unmanaged structs.
- Add `IsUnmanaged` check to `IsImmutable`
- Update struct tests to be managed types and add corresponding unmanaged tests
=> Fix unmanaged member deep cloning on .NET Framework.

src/Riok.Mapperly.Abstractions/MapDerivedTypeAttribute.cs, src/Riok.Mapperly.Abstractions/MapperConstructorAttribute.cs, src/Riok.Mapperly.Abstractions/MapperIgnoreAttribute.cs, src/Riok.Mapperly.Abstractions/MapperIgnoreSourceAttribute.cs, src/Riok.Mapperly.Abstractions/MapperIgnoreTargetAttribute.cs
Seal all configuration attributes as Mapperly reads the configuration via the syntax/symbols which does not work if an attribute is inherited. This could be a breaking change if one extends such an attribute, however, since it never worked with Mapperly, it should still be safe.
=> fix: seal all configuration attributes

.github/pull_request_template.md, src/Riok.Mapperly/Descriptors/MappingBuilders/DerivedTypeMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/DerivedTypeIfExpressionMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/DerivedTypeSwitchMapping.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDtoProjectionBaseType.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDtoProjectionTypeA.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDtoProjectionTypeB.cs, test/Riok.Mapperly.IntegrationTests/Mapper/ProjectionMapper.cs, test/Riok.Mapperly.IntegrationTests/Models/TestObjectProjectionBaseType.cs, test/Riok.Mapperly.IntegrationTests/Models/TestObjectProjectionTypeA.cs, test/Riok.Mapperly.IntegrationTests/Models/TestObjectProjectionTypeB.cs, test/Riok.Mapperly.IntegrationTests/ProjectionMapperTest.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/ProjectionMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/ProjectionMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/ProjectionMapperTest.DerivedTypesProjectionShouldTranslateToQuery_query.verified.sql, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/ProjectionMapperTest.DerivedTypesProjectionShouldTranslateToQuery_result.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/ProjectionMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/QueryableProjectionDerivedTypeTest.cs, test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionDerivedTypeTest.AbstractBaseClassDerivedTypesShouldWork#Mapper.g.verified.cs
Adds a new if + is expression save derived type mapping to add support for derived type mappings in expressions.
Closes https://github.com/riok/mapperly/issues/409
=> fix: support queryable projection mappings for derived type mappings

src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
Added a `NullReferenceException` with the message `"Sequence {nameof(source)}, contained a null value"` arm to `NullSubstitute` for element accessors. 
The error message could be improved, I considered `"Null value found inside sequence {nameof(source)}"`.
Fixes #413.
=> fix: throw NullReferenceException for element access

src/Riok.Mapperly/Descriptors/Mappings/UserDefinedNewInstanceMethodMapping.cs, test/Riok.Mapperly.Tests/_snapshots/DictionaryTest.DictionaryToCustomDictionaryWithPrivateCtorShouldDiagnostic#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyConstructorResolverTest.ClassToClassPrivateCtorShouldDiagnostic#Mapper.g.verified.cs
When `UserDefinedNewInstanceMethodMapping` cannot create an instance it generates an invalid throw throw statement. By replacing the enclosing `ThrowStatement` a normal throw statement is generated.
=> fix: prevent `throw throw` being generated.

src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableDeepCloningTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
If the source type is an array, the target type is an IEnumerable, the source should be cloned instead of casted
This also extracts deep cloning enumerable tests into a separate test class.
Fixes an issue similar to https://github.com/riok/mapperly/issues/426
=> fix: clone array when deepcloning is enabled and target is an IEnumerble

src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableDeepCloningTest.cs
Clones source enumerables if deep cloning is enabled by using `ToList`/`ToArray`.
Closes https://github.com/riok/mapperly/issues/426
=> fix: use ToList/ToArray to clone enumerable interfaces

src/Riok.Mapperly/Descriptors/MappingBuilders/CtorMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/CtorTest.cs
**Description**
`CtorMapping` will try to construct an object from itself using inaccessible constructors. This usually occurs with records because they all have protected constructors.
```C#
[Mapper(UseDeepCloning = true)]
public static partial class Mapper
{
public static partial MyRecord Map(MyRecord src);
public static partial MyClass Map(MyClass src);
}
public class MyClass
{
protected MyClass(MyClass myClass)
{
}
}
public record MyRecord
{
public int Value { get; set; }
}
```
```C#
// Generates
public static partial global::Riok.Mapperly.Sample.MyRecord Map(global::Riok.Mapperly.Sample.MyRecord src)
{
return new global::Riok.Mapperly.Sample.MyRecord(src); // invalid can't access constructor
}
public static partial global::Riok.Mapperly.Sample.MyClass …
```
=> Prevent mapping to inaccessible construtors

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.Tests/Mapping/CtorTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Exclude static constructors and only consider instance constructors to create new objects.
=> fix: only use instance constructors to create new object instances

src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
=> fix: existing dictionary and enumerable mapping should respect enabled conversion types

src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, src/Riok.Mapperly/Descriptors/Configuration.cs, src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs, src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/QueryableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/ObjectFactories/ObjectFactoryBuilder.cs, src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs, src/Riok.Mapperly/Descriptors/WellKnownTypes.cs, src/Riok.Mapperly/MapperGenerator.cs
**Description**
See #475
Add a `Dictionary<Type, INamedTypeSymbol?>` cache to `WellKnownTypes` to optimize `AttributeDataAccessor`.
**Benchmarks**
Benefits mappers with many mapping methods, saves 8ms for `LargeCompile` and saved 300 KB of memory. Doesn't look like `Compile` is effected.
**Old:**
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  1.563 ms | 0.0261 ms | 0.0244 ms |   82.0313 |  19.5313 |  169.32 KB |
| LargeCompile | 59.450 ms | 1.1351 ms | 1.1148 ms | 1428.5714 | 285.7143 | 9280.05 KB |
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- …
=> feat: cache attribute symbols

docs/docs/02-configuration/04-enum.mdx, docs/docs/98-contributing/05-common-tasks.md, src/Riok.Mapperly.Abstractions/EnumMappingStrategy.cs, src/Riok.Mapperly.Abstractions/MapEnumAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, src/Riok.Mapperly/Configuration/EnumMappingConfiguration.cs, src/Riok.Mapperly/Configuration/EnumValueMappingConfiguration.cs, src/Riok.Mapperly/Configuration/MapEnumAttributeData.cs, src/Riok.Mapperly/Configuration/MapperConfiguration.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/CastMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumCastMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFallbackValueMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringParseMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringSwitchMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumNameMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumToStringMapping.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.IntegrationTests/Mapper/TestMapper.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/DiagnosticMatcher.cs, test/Riok.Mapperly.Tests/Mapping/EnumFallbackValueTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs, test/Riok.Mapperly.Tests/Mapping/QueryableProjectionEnumTest.cs
=> enum is defined check and fallback values

src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityNonEnumerated.cs, src/Riok.Mapperly/Helpers/UniqueNameBuilder.cs
I noticed that `UniqueNameBuilder` would repeatedly copy a large `HashSet` whenever a subscope was created. Often, the child scope would generate one or two new names and then exit.
To counter this, I optimized `UniqueNamebuilder` to reference and check its parent scope. If there are few items in its parent, to copy its parents names and check its grandparents scope. By checking the parents scope we prevent a lot of copying to subscopes. By optionally copying the parent and using the grandparent we reduce the depth of the generated `UniqueNameBuilders` and keep the runing time of `New` down. However, instantiating the `UniqueNameBuilder` takes longer and uses more memory due to the copying.
This is a pretty micro benchmarky change and relies upon a parents scope not changing when a child …
=> feat: refactored `UniqueNameBuilder`

src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableSetTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
Closes https://github.com/riok/mapperly/issues/498
=> fix: map existing target sets correctly

src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/NullMemberMapping.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs
Use a non nullable path argument in the nameof expression.
Fixes #528
=> fix: generate nameof compatible member access

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs, src/Riok.Mapperly/Descriptors/Enumerables/CollectionType.cs
- Converted `CollectionTypeInfo` to a struct
- Removed duplicate `IImmutableQueue` and added `ImmutableSortedDictionary`
- Added check to `HasValidAddMethod` for types with known `Add` methods, otherwise all none `None` types return false. `None` types are manually checked for `Add` methods.
- `IsCountKnown` returns null for `IEnumerable`, "Length" for `Array`, `Span` and `Memory` and "Count" for all none `None` types. `None` types are manually checked for length properties.
- Added a special check for `string` to return `IEnumerable`, because string isn't actually a "collection" type but does implement `IEnumerable` and is marked `None` by `GetCollectionTypeInfo`. It would iterate thrrought every possible collection type causing a considerable slow down.
- Moved `GetEnumeratedType` into …
=> chore: optimize CollectionInfoBuilder

src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, src/Riok.Mapperly/Configuration/MapperConfiguration.cs, src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs, src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs, src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ParseMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/ObjectFactories/ObjectFactoryBuilder.cs, src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs, src/Riok.Mapperly/Descriptors/WellKnownTypes.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs, src/Riok.Mapperly/MapperGenerator.cs, src/Riok.Mapperly/Symbols/MemberPath.cs
Added member, mappable member and attribute caching to improve performance and reduce memory usage.
Splitting up changes from #530 
10ms time and 3000KB memory savings
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|-----------:|
|      Compile |  2.491 ms | 0.0391 ms | 0.0366 ms |  156.2500 |  31.2500 |  284.15 KB |
| LargeCompile | 64.276 ms | 1.2297 ms | 1.2628 ms | 1714.2857 | 714.2857 | 10713.9 KB |
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |   Allocated |
|------------- |----------:|----------:|----------:|----------:|---------:|------------:|
|      Compile |  2.640 ms | 0.0524 ms | 0.0490 ms |  179.6875 |  46.8750 |   320.39 KB |
| …
=> chore: add member, mappable member and attribute caching

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/LinqConstructorMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/LinqDictionaryMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/LinqEnumerableMapping.cs, src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs
Inspired [by Sytem.Text.Json](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/gen/Helpers/KnownTypeSymbols.cs#L237C13-L237C13) to use the known string of a method instead of looking it up via the compilation.
- `CollectionInfoBuilder` - used `SpecialType.System_Int32` instead of `types.Get<int>()`
- `EnumerableMappingBuilder` - use method string instead of retrieving the type and looking for a matching method, this has been done for ImmutableCollections, Collect methods and `Select`
- `DictionaryMappingBuilder`
- Use switch expression in `ResolveImmutableCollectMethod` to use `CollectionType`
- Use method string instead of retrieving the type and looking for a matching method.
- Fix typo `LinqDicitonaryMapping`
Related to #530
Note that I've used a branch where …
=> Use `string` for methods instead of `IMethodSymbol`

test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Under specific circumstances, when Mapperly attempts to map to a target, a private source members with greater flattening priority can override another public member. A later validation check would reject the mapping as the source is inaccessible, emitting a diagnostic.
#537 prevents this by only mapping accessable source members.
This PR contains a test to validate that the bug is fixed.
Fixes #521
=> fix: private members can override public members

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Helpers/NullableSymbolExtensions.cs, src/Riok.Mapperly/Helpers/SymbolExtensions.cs
Slightly microbenchmarky improvements, not sure about the  manual foreach loops
- Remove `FirstOrDefault` allocation from `SymbolExtensions.ImplementsGeneric` - 106KB - `Func<INamedTypeSymbol, Boolean>`
- Remove `Where` allocation from `SymbolAccessor.GetMappableMembers` - 76KB - `Func<ISymbol, Boolean>`
- Remove `Where` allocation from `SymbolAccessor.GetAttributes` - 150KB - `Func<AttributeData, Boolean>`
- Use non string comparison `NonNullableValueType` check
- Add `IsRefLike` check to `GetEnumeratedType`
- Remove unneeded `types.Get<int>()` call  from `CollectionInfoBuilder.FindCountProperty`
Related to #530
200 KB saved, little change in speed.
|       Method |      Mean |     Error |    StdDev |      Gen0 |     Gen1 |  Allocated |
|------------- …
=> chore: common linq loop allocations, add small optimisations 

src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedExistingTargetMethodMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceGenericTypeMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceMethodMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceRuntimeTargetTypeMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceRuntimeTargetTypeParameterMapping.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs, src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs
- Remove usage of `Get<PreserveReferenceHandler>()` from UserMethods, replace with a constant display string, simplifying logic and slightly improving memory usage (one less call to `WellKnownType.Get`).
- Reorder logic in `GetAttributes<T>` to get the symbols attributes before retrieving the attribute type. This way if the symbol doesn't have any attributes the symbol doesn't have to be retrieved.
=> chore: minor refactor for `GetAttributes` and UserMethods

docs/docs/configuration/enum.mdx, docs/package.json, src/Riok.Mapperly.Abstractions/MapperIgnoreSourceValueAttribute.cs, src/Riok.Mapperly.Abstractions/MapperIgnoreTargetValueAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Configuration/EnumMappingConfiguration.cs, src/Riok.Mapperly/Configuration/MapperConfiguration.cs, src/Riok.Mapperly/Configuration/MapperIgnoreEnumValueConfiguration.cs, src/Riok.Mapperly/Configuration/MappingConfigurationReference.cs, src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumCastMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumNameMapping.cs, src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/EnumIgnoreTest.cs, test/Riok.Mapperly.Tests/Mapping/QueryableProjectionEnumTest.cs, test/Riok.Mapperly.Tests/_snapshots/EnumTest.EnumToOtherEnumByNameWithoutOverlap.verified.txt
Adds new attributes `MapperIgnoreSourceValue` and `MapperIgnoreTargetValue` to ignore source/target enum values. This is especially useful for strict enum mappings (to ignore single values not present in the source and/or target without emitting a diagnostic).
Fixes #337
=> feat: add option to ignore enum values

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, src/Riok.Mapperly/MapperGenerator.cs, test/Riok.Mapperly.Tests/Generator/IncrementalGeneratorTest.cs, test/Riok.Mapperly.Tests/Mapping/MapperTest.cs
Emits RMG046 as an error if a language version < 9.0 is used.
Fixes #532
=> feat: diagnostic if an incompatible language version is used

docs/docs/configuration/mapper.mdx, src/Riok.Mapperly.Abstractions/IgnoreObsoleteMembersStrategy.cs, src/Riok.Mapperly.Abstractions/MapperAttribute.cs, src/Riok.Mapperly.Abstractions/MapperIgnoreObsoleteMembersAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly/Configuration/MapperConfiguration.cs, src/Riok.Mapperly/Configuration/PropertiesMappingConfiguration.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Symbols/FieldMember.cs, src/Riok.Mapperly/Symbols/IMappableMember.cs, src/Riok.Mapperly/Symbols/PropertyMember.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDto.cs, test/Riok.Mapperly.IntegrationTests/Mapper/DeepCloningMapper.cs, test/Riok.Mapperly.IntegrationTests/Mapper/ProjectionMapper.cs, test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs, test/Riok.Mapperly.IntegrationTests/Mapper/TestMapper.cs, test/Riok.Mapperly.Tests/Mapping/IgnoreObsoleteTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs, test/Riok.Mapperly.Tests/TestSourceBuilder.cs, test/Riok.Mapperly.Tests/TestSourceBuilderOptions.cs
Resolves #284 and #450.
- Created `MapperIgnoreObsoleteMembersAttribute` and added `IgnoreObsoleteStrategy` to `MapperAttribute`. Updated `MembersMappingBuilderContext` to add the derecated members to there respective `Ignored*MemberNames`.
- Updated `FieldMember` and `PropertyMember` to expose the underlying symbol.
- Added unit tests
- Mapper attribute config is overriden by the method configuration.
- By default `IgnoreObsoleteStrategy` is none so deprecated members are treated as normal.
- The method attribute has a default parameters of `Both`  
```C#
[MapperIgnoreObsoleteMembers] partial B Map(A source);`
```
>  blanket ignore all obsolete members except when [MapProperty] is used?
Haven't done this yet, I'm not 100% sure how `MemberConfigsByRootTargetName` works to match the …
=> feat: add IgnoreObsoleteMembers and `MapProperty` maps ignored Target

src/Riok.Mapperly/MapperGenerator.cs
Reorder `MapperGenerator` to get the `MapperAttribute` with `WellKnowTypes`
=> chore: use `WellKnowTypes` to get `MapperAttribute`

src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Helpers/NullableSymbolExtensions.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
Added check to `SymbolAccessor` for nullable value types. This way `Nullable<T>.Value` will not be treated as a member resulting in invalid auto resolved flattenings
Fixes #572 & #571
=> fix: `Nullable<T>.Value` is no longer treated as a member

src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/NullDelegateExistingTargetMapping.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/MapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.Tests/Mapping/NullableTest.cs
Modify `NullDelegateExistingTargetMapping` to check if the body contains any elements, not generating the if statement when empty.
Fixes #497
=> fix: prevent generation of empty if not null statements

src/Riok.Mapperly/Symbols/MemberPath.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
When using `MapProperty` to map to deeply nested nullable members, Mapperly will generate a series of identical statements initializing the same field. This is because all the `MemberNullAssignmentInitializerMapping` mistakenly use the same `IReadOnlyCollection` so will all update the same path.
Added a `ToArray` to `ObjectPathNullableSubPaths` to collect the paths into separate collections.
```C#
var target = new global::B();
target.Value.Nested ??= new();
target.Value.Nested ??= new();
target.Value.Nested ??= new();
target.Value.Nested.Id = source.MyValueId;
target.Value.Nested.Id2 = source.MyValueId2;
return target;
```
=> fix: incorrect initialization for nullable nested memberpath unflattening

src/Riok.Mapperly/Descriptors/Mappings/NullDelegateMapping.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
As suggested added null supression to `NullDelegateMapping` when accessing array elements.
Fixes #416
=> fix: disable warning when iterating nullable array elements

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/SpanMappingBuilder.cs
Minor nit picks
- Use `HasImplicitAdd` in `SpanMappingBuilder` instead of manually checking for valid `Add` methods again.
- Optimize `HasValidAddMethod` to use the implemented types to check before searching for an implicit add method.
=> chore: use `HasImplicitAdd` and optimize `HasValidAddMethod`

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewValueTupleMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
Use a cache dictionary for the mappable members by name. This increases the performance of mapping classes with lots of members, since the lookup by member name is now constant time instead of linear.
=> fix: improve performance for member resolution

src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.ArrayToReadOnlyCollectionShouldUpgradeNullability#Mapper.g.verified.cs
Modified `ArrayForMapping` to use the correct element nullability in the method signature.
This could be fixed in `NullableSymbolExtensions` by making it check for `IEnumerable` types. Doing this would create a dependency on `SymbolAccessor` or `WellKnownTypes` and probably create a small performance hit. If #588 has this problem this approach could be revisited.
Fixes #229
=> fix: arrays use correct element nullability

docs/docs/configuration/flattening.md, docs/docs/configuration/mapper.mdx, docs/src/plugins/rehype/rehype-faq/index.js, src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
Introduces experimental full nameof support.
See #401.
This would allow simpler `MapProperty` attributes for nested properties:
`[MapProperty(nameof(@A.B.C), nameof(@D.E.F)]` would be the same as `[MapProperty(new[]{nameof(A.B), nameof(A.B.C)}, new[]{nameof(D.E), nameof(D.E.F)}]`.
=> feat: introduce experimental full nameof support

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Added check for if a nested value type is being modified.
Probably not a common issue so I went with a diagnostic.
I considered nested chain assignment or a `with` expression ie `target.NestedValue = target.NestedValue with { StringValue = src.StringValue };` (can repeatedly chain)
Fixes #516
=> fix: add modifying nested struct diagnostic

.github/workflows/benchmark.yml, .github/workflows/code-ql.yml, .github/workflows/conventional-commits.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
* Run sample in ci to ensure it is valid
* Run benchmarks only if related files changed
* Cancel in-progress concurrent actions
* Move dotnet lint job to lint workflow to not run it on main
=> chore: run sample in ci to ensure it is valid

build/package.sh, src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, test/Riok.Mapperly.Tests/TestHelper.cs
=> fix: resolve configuration enums directly to fix VS but crashing the source generator

src/Riok.Mapperly.Abstractions/MapEnumValueAttribute.cs, test/Riok.Mapperly.IntegrationTests/Dto/TestEnumDtoAdditionalValue.cs, test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/StaticMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/StaticMapperTest.SnapshotGeneratedSource.verified.cs
When you want to specify multiple `MapEnumValueAttribute` you are not allowed by compiler
=> Add AllowMultiple into MapEnumValueAttribute

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
- Add check to container builder context for readonly members
- Added test
Fixes #653
=> fix: prevent null initializing readonly members

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs
Using `ImplementsGeneric` on external types will erase the nullable annotation of an array element type. This is used in  `CollectionInfosBuilder.GetEnumeratedType` where the resulting enumerated type is used by `EnumerableMappingBuilder` to map the element types of two collections.
This caused a rare issue where an array collection would be treated as if it had a nullable element type.
Fixes #690
=> fix: generate correct nullability for external array elements

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/AnalyzerReleases.Unshipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/IgnoreObsoleteTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs
Ignored members could also be explicitly mapped, but this may not be intended. This change adds warning level diagnostic messages when either a source or a target member is in that situation, but should not alter the behaviour of the library.
Fixes #512 (using the approach specified in its description)
=> feat: generate diagnostic warning when ignored members are explicitly mapped

src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringSwitchMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachSetDictionaryExistingTargetMapping.cs, src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Condition.cs, src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Null.cs, test/Riok.Mapperly.Tests/GeneratedMethod.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumFallbackValueTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableDeepCloningTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableExistingTargetTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableSetTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/Mapping/MemoryTest.cs, test/Riok.Mapperly.Tests/Mapping/NullableTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs, test/Riok.Mapperly.Tests/Mapping/ParseTest.cs, test/Riok.Mapperly.Tests/Mapping/SpanTest.cs, test/Riok.Mapperly.Tests/Mapping/ValueTupleTest.cs
Remove `NoramlizeWhitespace` in unit tests to ensure correct formatting in unit tests.
Rel. https://github.com/riok/mapperly/pull/746#discussion_r1322993775
Additional changes in formatting to https://github.com/riok/mapperly/pull/706:
* Enum parsing mapping: space in braces is removed: `{} s when s.Equals(nameof(source.Value1), StringComparison.OrdinalIgnoreCase) => ...` instead of `{ } s when s.Equals(nameof(source.Value1), StringComparison.OrdinalIgnoreCase) => ...`.
Changes to fix formatting introduced in #706:
* Enum parsing mapping: Adds a space between `{}` and `s`
* Dictionary mapping if only explicit interface implementation: indent variable declaration correctly
* Indent throw argument null exception throws correctly
=> fix: fix spacing for casts and enum parse mappings

test/Directory.Build.props, test/Riok.Mapperly.Tests/ModuleInitializer.cs
Use DiffPlex for snapshot diffs to get compacter, better readable results.
=> chore: add diffplex to render test snapshot diffs

.github/workflows/benchmark.yml, .github/workflows/code-ql.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Directory.Build.props, benchmarks/Riok.Mapperly.Benchmarks/Riok.Mapperly.Benchmarks.csproj, build/package.sh, docs/docs/configuration/generated-source.mdx, docs/prebuild.ts, global.json, src/Directory.Build.props, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/IDelegateUserMapping.cs, src/Riok.Mapperly/Riok.Mapperly.Roslyn4.7.props, test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj, test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery_NET8_0.verified.sql, test/Riok.Mapperly.Templates.Tests/PreserveReferenceHandlerTest.cs, test/Riok.Mapperly.Tests/Riok.Mapperly.Tests.csproj
Upgrades to .net8.0 / C#12 preview / Roslyn 4.7.
Fixes #682
=> feat: support for Roslyn 4.7

test/Riok.Mapperly.Tests/Mapping/CtorTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs
Adds support for C#12 primary constructors.
Depends on https://github.com/riok/mapperly/pull/718. Probably await .NET 8.0 RC1.
Fixes #684
=> feat: C#12 primary constructors support

src/Riok.Mapperly/Symbols/MethodParameter.cs, test/Riok.Mapperly.Tests/Mapping/MapperTest.cs
- Added `RestrictedNameHelper` which is called by the `MethodParameter` constructor
- `ToSafeName` checks the input for every restricted keyword. This should be really fast in .Net 8 but I doubt it will make any impact in prior versions
- Added tests
Fixes #402
=> fix: check for arguments with restricted keywords

src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs
Use the `IEnumerable` constructor if key and value mapping is synthetic. 
```C#
// New
return new global::System.Collections.Generic.Enumerable.Dictionary<string, long>(source);
// Old
var target = new global::System.Collections.Generic.Dictionary<string, long>(source.Count);
foreach (var item in source)
{
target[item.Key] = item.Value;
}
return target;
```
See #689
=> feat: use `IEnumerable` `Dictionary` constructor

src/Riok.Mapperly.Abstractions/MapperAttribute.cs, src/Riok.Mapperly.Abstractions/MapperRequiredMappingAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly.Abstractions/RequiredMappingStrategy.cs, src/Riok.Mapperly/Configuration/MapperConfiguration.cs, src/Riok.Mapperly/Configuration/MapperConfigurationMerger.cs, src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs, src/Riok.Mapperly/Configuration/PropertiesMappingConfiguration.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs, test/Riok.Mapperly.IntegrationTests/Models/TestObject.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.RunMappingShouldWork_NET6_0.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.RunMappingShouldWork_NET6_0.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunExtensionMappingShouldWork_NET6_0.verified.txt, test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunMappingShouldWork_NET6_0.verified.txt, test/Riok.Mapperly.Tests/Helpers/MapperConfigurationBuilderTest.cs, test/Riok.Mapperly.Tests/Mapping/RequiredMappingTest.cs, test/Riok.Mapperly.Tests/TestSourceBuilder.cs, test/Riok.Mapperly.Tests/TestSourceBuilderOptions.cs
Disable the unmapped source/target member warning on a mapper or method level. ie `[MapperAllowUnmapped(AllowUnmapped.Source)]` will not warn about unmapped source members and will still automatically map members.
Currently using `AllowUnmapped` as a placeholder. I haven't done integration tests, documentation, xml docs etc.
Fixes #687 / #677
=> feat: add strict mapping

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyIgnoreTest.cs
Mapperly does not support nested ignores. To prevent confusion, I've added 2 diagnostics that will warn the user when one is found.
- This could be one single diagnostic for both source and target ignores, not sure if a slightly more specific warning is worth it.
- If a nested ignore is found the usual `IgnoredTargetMemberNotFound`/`IgnoredSourceMemberNotFound` diagnostics will not be emitted.
Fixes #815, #814
=> feat: add diagnostic for nested ignores

src/Riok.Mapperly/Symbols/SetterMemberPath.cs, test/Riok.Mapperly.Tests/Mapping/UnsafeAccessorTest.cs
Prevents the invalid generation of set to a `private set` property if `~MemberVisibility.Accessible` is used.
Fixes #932
=> feat: fix incorrect `private set` when `~MemberVisibility.Accessible` is used

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/MemberNullDelegateAssignmentMapping.cs, src/Riok.Mapperly/Symbols/SetterMemberPath.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/CircularReferenceMapperTest.SnapshotGeneratedSource.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/DeepCloningMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource_NET8_0.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs, test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource_NET6_0.verified.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.ArrayToCollectionShouldUpgradeNullability#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.ArrayToReadOnlyCollectionShouldUpgradeNullability#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.CollectionToReadOnlyCollectionShouldUpgradeNullability#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.ShouldUpgradeNullabilityInDisabledNullableContextInSelectClause#Mapper.g.verified.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyNullableTest.ShouldUpgradeNullabilityInDisabledNullableContextInNestedProperty#Mapper.g.verified.cs
If `AllowNullPropertyAssignment` is `true`, respect it correctly (set target members to null) if the mapping for the property is not accepting `null` values and is not synthetic.
This could have a big impact, we should probably release this as breaking change 🤔 
Fixes #803
=> fix: Respect AllowNullPropertyAssignment correctly when mapping code is not a direct assignment

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/INewInstanceBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewInstanceBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewInstanceContainerBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, test/Riok.Mapperly.Tests/Mapping/CtorTest.cs
Support for
```cs
public class Mapping
{
[MapProperty(nameof(A.BId), nameof(B.Id))] // notice target ctor parameter is "id", but `MapProperty` target is "Id"
private partial B Map(A source);
}
class A
{
public long BId { get; }
}
class B
{
public long Id { get; }
public B(long id) { Id = id; }
}
```
Fixes #952
=> feat: support `MapProperty` with `nameof` for CtorMapping

docs/docs/configuration/generic-mapping.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/RuntimeTargetTypeMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceGenericTypeMapping.cs, test/Riok.Mapperly.Tests/Mapping/GenericTest.cs
Generic mapping is selecting target methods only by type argument constraint. This PR filters them also by LSP type compatibility.
Right now, the mapping does not produce valid code when e.g. source is a specific abstract type (not the `object`). And your mapper has e.g. enum mapping. The compiler then complains: `Error CS8121 : An expression of type 'TheClass' cannot be handled by a pattern of type 'TheEnum'.` on generated code that looks like this:
```cs
partial T Map<T>(TheClass source)
{
return source switch
{
global::TheEnum x when typeof(T).IsAssignableFrom(typeof(global::TheEnum)) => (T)(object)MapToTheEnum(x),
};
}
```
=> feat: generate generic mapping only with LSP compatible methods

docs/docs/getting-started/installation.mdx, src/Riok.Mapperly/Riok.Mapperly.targets
This ensures naming consistency. Otherwise the runtime term is duplicated.
=> fix: remove Runtime suffix of MapperlyAbstractionsScope msbuild option

docs/docs/configuration/enum.mdx, docs/docs/configuration/mapper.mdx, src/Riok.Mapperly/Configuration/EnumMappingConfiguration.cs, src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumRequiredMappingTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs
Fixes https://github.com/riok/mapperly/issues/811
Adds support for `RequiredMappingStrategy` for enum members.
=> feat: support required mapping strategies on enums

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs, src/Riok.Mapperly/Configuration/MappingConfiguration.cs, src/Riok.Mapperly/Configuration/MemberMappingConfiguration.cs, src/Riok.Mapperly/Configuration/MembersMappingConfiguration.cs, src/Riok.Mapperly/Configuration/StringMemberPath.cs, src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IMembersBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewValueTupleMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DirectAssignmentMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ExplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ImplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/MemoryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/NewInstanceObjectMemberMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/QueryableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/SpanMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ToObjectMappingBuilder.cs, src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs
Closes https://github.com/riok/mapperly/issues/868
* Refactors and simplifies the internal configuration mechanisms
* Emits diagnostics if property configurations are placed on queryable projection mappings
* Emits diagnostics if enum configurations are placed on object mappings
* Emits diagnostics if property configurations are placed on enum mappings
=> feat: validate usage of MapProperty attributes on enum and queryable mapping methods

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs, src/Riok.Mapperly/Configuration/MemberMappingConfiguration.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
Adds a new diagnostic for invalid map property attribute usages (eg. when using Use and StringFormat at the same time).
=> feat: report a diagnostic for invalid MapPropertyAttribute usages

docs/docs/configuration/mapper.mdx
=> docs: Typo on the word 'member' in mapper.mdx

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/MemberNullDelegateAssignmentMapping.cs, test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs, test/Riok.Mapperly.Tests/Mapping/ValueTupleTest.cs
=> fix: correctly assign null if target is nullable instead of throwing

src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBuilders/UseNamedMappingBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/ObjectNestedPropertyTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyUseNamedMappingTest.cs
Adds warnings `RMG072` and `RMG073` when the types of a referenced mapping do not exactly match (except for nullability)  the member types.
Closes #1254
=> feat: add a warning when a referenced mapping types do not match

src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Null.cs
Fixes parts of #1255
Tested with https://github.com/riok/mapperly/pull/1262
=> fix: correct syntax in nameof clause of throw null exceptions

docs/docs/configuration/mapper.mdx
Note that the runtime attribute scope needs to be set if the mapper ignore attribute is in another dll
Relates #1252
=> docs: improve mapper ignore attribute description

src/Riok.Mapperly/Descriptors/ObjectFactories/ObjectFactoryCollection.cs, test/Riok.Mapperly.Tests/Mapping/ObjectFactoryTest.cs
Includes the source and target type when caching the resolved object factory for a given type pair instead of only the target type. This fixes a bug when using multiple object factories with the same return type but different parameter types and multiple mappings using these different object factories.
Fixes #1312
=> fix: fixes using the wrong object factory when multiple factories with the same target type but different source types are used

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/IgnoreAttributeTest.cs, test/Riok.Mapperly.Tests/Mapping/IgnoreObsoleteTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyFlatteningTest.ManualUnflattenedPropertyTargetPropertyPathWriteOnlyShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.InitOnlyPropertyWithConfigurationNotFoundSourcePropertyShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.InitOnlyPropertyWithMultipleConfigurationsShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.InitOnlyPropertyWithPathConfigurationsShouldDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.ShouldIgnoreReadOnlyPropertyOnTargetWithDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetPathGetterShouldIgnoreAndDiagnostic.verified.txt, test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetSetterShouldIgnoreAndDiagnostic.verified.txt
Rel #631
Removes mentioning "member" and "MapPropertyAttribute" from diagnostic messages as this would be constant values and "MapValueAttribute" with #631
=> fix: adjust diagnostic messages to be correct when applied with MapValue

docs/docs/breaking-changes/3-0.md, docs/docs/breaking-changes/4-0.md, src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, src/Riok.Mapperly/Symbols/MappableMember.cs, test/Riok.Mapperly.Tests/Mapping/ObjectNoMemberMappingsTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs, test/Riok.Mapperly.Tests/TestHelperOptions.cs
* Removes RMG026 and simply ignores indexed properties to simplify referencable member mapping logic
=> fix: ignore indexed properties

docs/docs/breaking-changes/4-0.md, src/Riok.Mapperly.Abstractions/MappingConversionType.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs, test/Riok.Mapperly.Tests/Mapping/EnumTest.cs
BREAKING CHANGE: For enum underlying type conversions the new EnumUnderlyingType conversion is used instead of ExplicitCast
=> feat!: add enum underlying type conversion

docs/docs/breaking-changes/4-0.md, docs/docs/configuration/flattening.md, src/Riok.Mapperly.Abstractions/MapPropertyAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Unshipped.txt, src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs, test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs, test/Riok.Mapperly.IntegrationTests/Mapper/TestMapper.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
* Marks `MapPropertyattribute.ctor(string[], string[])` as obsolete
* Adds `MapPropertyAttribute.ctor(string[], string)`
* Adds `MapPropertyAttribute.ctor(string, string[])`
=>  fix: Replace invalid MapPropertyAttribute constructors with valid versions

src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs, test/Riok.Mapperly.Tests/Helpers/InlineExpressionRewriterTest.cs
When using `Use = nameof()`, which contains casting, e.g. `((MyEnum) value & MyEnum.OptionA) > 0` generated mapping does not resolve the fully qualified type of the casted type.
=> Support inline expression with casting

docs/docs/breaking-changes/4-0.md, src/Riok.Mapperly/Configuration/StringMemberPath.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NestedMappingsContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewValueTupleConstructorBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewValueTupleExpressionBuilderContext.cs, src/Riok.Mapperly/Descriptors/MemberPathCandidateBuilder.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Helpers/ImmutableEquatableArray.cs, test/Riok.Mapperly.Tests/Descriptors/MemberPathCandidateBuilderTest.cs
* Only compute member name permutations until a match is found
* Limit number of computed member permutations
Fixes #1444
=> fix: improve member matching performance for member names with lots of upper case letters

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
=> fix: initialize nullable values when assigning null to a child member

docs/docs/configuration/enum.mdx, src/Riok.Mapperly.Abstractions/MapEnumValueAttribute.cs, src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt, src/Riok.Mapperly/AnalyzerReleases.Shipped.md, src/Riok.Mapperly/Configuration/EnumValueMappingConfiguration.cs, src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/EnumMappingDiagnosticReporter.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToEnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumToStringMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/StringToEnumMappingBuilder.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumFromStringSwitchMapping.cs, src/Riok.Mapperly/Descriptors/Mappings/Enums/EnumToStringMapping.cs, src/Riok.Mapperly/Descriptors/SymbolAccessor.cs, src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs, test/Riok.Mapperly.Tests/Mapping/EnumToEnumExplicitMapTest.cs, test/Riok.Mapperly.Tests/Mapping/EnumToStringExplicitMapTest.cs, test/Riok.Mapperly.Tests/Mapping/StringToEnumExplicitMapTest.cs
Added support for enum from/to string explicit mappings using MapEnumValueAttribute
Fixes #1476
=> 1476 strings in enum value attribute

src/Riok.Mapperly/Descriptors/InlineExpressionRewriter.cs, test/Riok.Mapperly.Tests/Helpers/InlineExpressionRewriterTest.cs
Inlining of
```cs
public class Test
{
public IReadOnlyCollection<A> MapExpression(A value) => Array.Empty<A>();
}
```
Produces:
`global::System.Array.Empty()`
instead of
`global::System.Array.Empty<global::A>()`
=> Support inlining of method with generic type arguments

.editorconfig, docs/static/_headers
Adds security relevant headers to the documentation webpage using the cloudflare pages _headers file.
Disables the access-control-allow-origin header, added by CF pages by default.
Use hashes for docusaurus inlined scripts
=> docs: add security headers

docs/docs/breaking-changes/4-0.md, src/Riok.Mapperly.Abstractions/MapPropertyAttribute.cs, test/Riok.Mapperly.Abstractions.Tests/_snapshots/PublicApiTest.PublicApiHasNotChanged.verified.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNestedTest.cs
Removes the obsolete attribute from `MapProperty.ctor(string[], string[]`) and adds tests to ensure nested to nested mappings work correct.
See https://github.com/riok/mapperly/pull/1354#issuecomment-2411370018.
=> Removes the obsolete attribute from `MapProperty.ctor(string[], string[]`)

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueMethodTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueTest.cs
=> handle nullable value types with MapValueAttribute and methods correct

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs
References types which are not available in netstandard2.0 with their full name and tries to load them at runtime.
Fixes #1549
=> fix: lazy load types which are not available on netstandard2.0

.github/ISSUE_TEMPLATE/bug_report.md
Adds a checklist and diagnostics to the bug template.
Diagnostics are often relevant to identify the problem faster.
The checklist should prevent duplicated issues and already fixed ones.
=> add diagnostics and checklist to the bug template

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersContainerBuilderContext.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
Made changes to store `IMemberAssignmentMappingContainer` along with the `MemberPath` to keep track of nullable member initializations.
Fixes #1650
=> fix: initialize nullable members for nested containers

docs/docs/configuration/mapper.mdx, docs/docs/configuration/queryable-projections.mdx, src/Riok.Mapperly/Configuration/MapperConfigurationReader.cs, src/Riok.Mapperly/Configuration/MappingConfiguration.cs, src/Riok.Mapperly/Descriptors/InlineExpressionMappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/DirectAssignmentMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ExplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ImplicitCastMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/MemoryMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/SpanMappingBuilder.cs, src/Riok.Mapperly/Descriptors/MappingBuilders/ToObjectMappingBuilder.cs, src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs, test/Riok.Mapperly.Tests/Mapping/QueryableProjectionNullableTest.cs, test/Riok.Mapperly.Tests/_snapshots/QueryableProjectionNullableTest.NestedPropertyWithDeepCloneable#Mapper.g.verified.cs
Never apply deep cloning to queryable projections, as these are projections and deep cloning doesn't have an effect on the projection.
=> feat: do not apply deep cloning to queryable projection mappings

test/Directory.Build.props, test/Riok.Mapperly.Abstractions.Tests/Helpers/ArchTestResultAssertions.cs
See https://github.com/riok/mapperly/pull/1703#issuecomment-2660483137
=> chore: revert fluent assertions to v7 due to license concerns

docs/docs/contributing/index.md
A little fix in the documentation.
I was confused when reading the contribution guide by the word "OpenThread". I assume you were inspired by OpenThread guidelines and that an occurrence was not replaced.
So I fix it to avoid futur misleading.
=> fix(doc): In page "contributing", replace remaining occurence of "OpenThread"

test/Riok.Mapperly.Tests/Mapping/IncludeMappingConfigurationTest.cs, test/Riok.Mapperly.Tests/Mapping/NamedMappingTest.cs, test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
I found several syntax errors in the test input sources. Some are made by me. I would like to push a fix.
I found this while investigating `CreateNameOfMemberPath` and whether it could be used for the full path referencing of other methods. Interestingly, there were too many cases when the fallback code ran, which led to this realization. The fallback still runs, but in cases where the error is intentional.
=> Fix syntax errors in tests

docs/docs/configuration/additional-mapping-parameters.mdx
Rel. https://github.com/riok/mapperly/issues/1765#issuecomment-3122186666
=> docs: add info that derived type mappings do not support additional type parameters
