src/Riok.Mapperly/Descriptors/MappingBuilder/DictionaryMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/EnumerableMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs
src/Riok.Mapperly/Descriptors/Mappings/ArrayForMapping.cs
src/Riok.Mapperly/Descriptors/MethodNameBuilder.cs
src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
test/Riok.Mapperly.Tests/_snapshots/EnumerableTest.ShouldUpgradeNullabilityInDisabledNullableContextInSelectClause.verified.cs

Improve enumerable mapping performance by using for loops without an enumerator for array to array mappings instead of linq based select+collect

feat: improve enumerable performance

---

src/Riok.Mapperly/Descriptors/MappingBuilder/UserMethodMappingBuilder.cs
test/Riok.Mapperly.Tests/Mapping/UserMethodTest.cs
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.WithClassBaseTypeShouldWork.00.verified.cs
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.WithClassBaseTypeShouldWork.01.verified.cs

Closes https://github.com/riok/mapperly/issues/38

feat: support partial base classes

---

src/Riok.Mapperly/Descriptors/Mappings/EnumFromStringMapping.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.Tests/Mapping/EnumTest.cs

fix: add System namespace to Enum

---

README.md
src/Riok.Mapperly/AnalyzerReleases.Shipped.md
src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs
src/Riok.Mapperly/Descriptors/MapperDescriptor.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/UserMethodMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilderContext.cs
src/Riok.Mapperly/Descriptors/Mappings/MethodMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UserDefinedExistingInstanceMethodMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UserDefinedNewInstanceMethodMapping.cs
src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs
src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
src/Riok.Mapperly/Emit/SourceEmitter.cs
src/Riok.Mapperly/Emit/SourceEmitterContext.cs
test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs
test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs
test/Riok.Mapperly.IntegrationTests/MapperTest.cs
test/Riok.Mapperly.IntegrationTests/StaticMapperTest.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunExtensionMappingShouldWork.verified.txt
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunMappingShouldWork.verified.txt
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.Tests/Mapping/UserMethodTest.cs
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.InstanceMapperShouldEmitDiagnosticForStaticMethods.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.InstanceMapperShouldEmitDiagnosticForStaticMethods.01.verified.cs
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.StaticMapperShouldEmitDiagnosticForInstanceMethods.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/UserMethodTest.StaticMapperShouldEmitDiagnosticForInstanceMethods.01.verified.cs

Supports static mappers and extension mapping methods.
Mixed mappers (instance mappers with static mapping methods) are not supported.

feat: static mappers

---

src/Riok.Mapperly/Descriptors/MappingBuilder/EnumerableMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/NullableMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/ObjectPropertyMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/UserMethodMappingBuilder.cs
src/Riok.Mapperly/Descriptors/Mappings/DirectAssignmentMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/NullDelegateMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/PropertyMappings/NullPropertyMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/TypeMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UserDefinedNewInstanceMethodMapping.cs
test/Riok.Mapperly.Tests/Mapping/NullableTest.cs

Closes https://github.com/riok/mapperly/issues/102

fix: nullable disabled enumerable target duplicate mapping

---

src/Riok.Mapperly/Descriptors/MemberPathCandidateBuilder.cs
test/Riok.Mapperly.Abstractions.Test/MapPropertyAttributeTest.cs
test/Riok.Mapperly.Tests/Descriptors/MemberPathCandidateBuilderTest.cs
test/Riok.Mapperly.Tests/Descriptors/MethodNameBuilderTest.cs
test/Riok.Mapperly.Tests/Helpers/EnumerableExtensionsTest.cs
test/Riok.Mapperly.Tests/Helpers/StringChunkerTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyFlatteningTest.cs
test/Riok.Mapperly.Tests/Mapping/UserMethodTest.cs

fix: prefer property without auto flattening

---

src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs
src/Riok.Mapperly/Descriptors/MapperDescriptor.cs
src/Riok.Mapperly/MapperGenerator.cs
test/Riok.Mapperly.Tests/Mapping/MapperTest.cs
test/Riok.Mapperly.Tests/_snapshots/MapperTest.SameMapperNameInMultipleNamespacesShouldWork.00FooBarMapper.g.verified.cs
test/Riok.Mapperly.Tests/_snapshots/MapperTest.SameMapperNameInMultipleNamespacesShouldWork.01FooBarMapper1.g.verified.cs

fix: support multiple mappers with the same name in different namespaces

---

README.md
src/Riok.Mapperly/Descriptors/MappingBuilder/NewInstanceObjectPropertyMappingBuilder.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs

fix: deprioritize constructors marked as obsolete

---

src/Riok.Mapperly/Descriptors/MappingBuilder/ObjectPropertyMappingBuilder.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateSourceGetterShouldIgnoreAndDiagnostic.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateSourceGetterShouldIgnoreAndDiagnostic.01Mapper.g.verified.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateSourcePathGetterShouldIgnoreAndDiagnostic.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateSourcePathGetterShouldIgnoreAndDiagnostic.01Mapper.g.verified.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetPathGetterShouldIgnoreAndDiagnostic.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetPathGetterShouldIgnoreAndDiagnostic.01Mapper.g.verified.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetSetterShouldIgnoreAndDiagnostic.00.verified.txt
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithPrivateTargetSetterShouldIgnoreAndDiagnostic.01Mapper.g.verified.cs

fix: ignore accessible source properties with inaccessible getters and accessible target properties with inaccessible getters

---

src/Riok.Mapperly/AnalyzerReleases.Unshipped.md
src/Riok.Mapperly/Descriptors/MappingBuilder/NewInstanceObjectPropertyMappingBuilder.cs
src/Riok.Mapperly/Diagnostics/DiagnosticDescriptors.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.RequiredPropertySourceNotFoundShouldDiagnostic#Mapper.g.verified.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyInitPropertyTest.RequiredPropertySourceNotFoundShouldDiagnostic.verified.txt

willing to add some more tests if neccessary

feat: Required Properties (C# 11)

---

src/Riok.Mapperly/Descriptors/MappingBuilder/DictionaryMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilder/EnumerableMappingBuilder.cs
src/Riok.Mapperly/Descriptors/WellKnownTypes.cs
test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs

Closes https://github.com/riok/mapperly/issues/247

feat: support IList<T>, List<T> and IReadOnlyList<T> targets

---

docs/docs/02-configuration/02-static-mappers.md
docs/docs/02-configuration/06-user-implemented-methods.md
docs/docs/02-configuration/11-conversions.md
src/Riok.Mapperly.Abstractions/MappingConversionType.cs
src/Riok.Mapperly.Abstractions/PublicAPI.Shipped.txt
src/Riok.Mapperly/Descriptors/MappingBuilders/DateTimeToDateOnlyMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/DateTimeToTimeOnlyMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs
src/Riok.Mapperly/Descriptors/WellKnownTypes.cs
test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs
test/Riok.Mapperly.IntegrationTests/Dto/TestObjectDto.cs
test/Riok.Mapperly.IntegrationTests/Helpers/PortableDateOnlyConverter.cs
test/Riok.Mapperly.IntegrationTests/Helpers/PortableTimeOnlyConverter.cs
test/Riok.Mapperly.IntegrationTests/Mapper/StaticTestMapper.cs
test/Riok.Mapperly.IntegrationTests/Mapper/TestMapper.cs
test/Riok.Mapperly.IntegrationTests/Models/TestObject.cs
test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj
test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.RunMappingShouldWork.verified.txt
test/Riok.Mapperly.IntegrationTests/_snapshots/MapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunExtensionMappingShouldWork.verified.txt
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.RunMappingShouldWork.verified.txt
test/Riok.Mapperly.IntegrationTests/_snapshots/StaticMapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.Tests/Mapping/DateTimeTest.cs

Closes https://github.com/riok/mapperly/issues/243

feat: datetime to dateonly and timeonly mapping

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectPropertyMappingBodyBuilder.cs
test/Riok.Mapperly.Tests/Mapping/NullableTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs

fix: resolve user defined mappings for init properties with correct nullability

---

src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
test/Riok.Mapperly.Tests/Mapping/DictionaryTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyTest.WithManualMappedNotFoundSourcePropertyShouldDiagnostic.verified.txt

Closes https://github.com/riok/mapperly/issues/283

fix: dont map to read only dictionaries

---

src/Riok.Mapperly/Descriptors/MapperDescriptor.cs
src/Riok.Mapperly/Emit/SourceEmitter.cs
src/Riok.Mapperly/MapperGenerator.cs
test/Riok.Mapperly.IntegrationTests/Mapper/NestedMapper.cs
test/Riok.Mapperly.IntegrationTests/NestedMapperTest.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/NET_48/NestedMapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_4_OR_LOWER/NestedMapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.IntegrationTests/_snapshots/Roslyn_4_5/NestedMapperTest.SnapshotGeneratedSource.verified.cs
test/Riok.Mapperly.Tests/Mapping/MapperTest.cs
test/Riok.Mapperly.Tests/_snapshots/MapperTest.MapperInNestedClassShouldWork#CarFeature.Mappers.CarMapper.g.verified.cs

feat: support nested mappers

---

src/Riok.Mapperly.Abstractions/MapperAttribute.cs

Resolves https://github.com/riok/mapperly/issues/369

docs: correct UseDeepCloning docs

---

src/Riok.Mapperly/Helpers/SymbolExtensions.cs
test/Riok.Mapperly.Tests/Mapping/ObjectFieldTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs

fix: ignore static fields and properties

---

dotnet-tools.json

Closes https://github.com/riok/mapperly/issues/314

chore: upgrade dotnet tools

---

dotnet-tools.json

upgrade xmldoc2markdown to fix generated api documentation issues

docs: upgrade xmldoc2markdown

---

src/Riok.Mapperly/Descriptors/UserMethodMappingExtractor.cs
test/Riok.Mapperly.Tests/Mapping/RuntimeTargetTypeMappingTest.cs

Closes https://github.com/riok/mapperly/issues/421

fix: ignore user implemented generic methods

---

src/Riok.Mapperly/Helpers/SymbolExtensions.cs
test/Riok.Mapperly.Tests/Mapping/DirectAssignmentDeepCloningTest.cs
test/Riok.Mapperly.Tests/Mapping/SpecialTypeDeepCloningTest.cs
test/Riok.Mapperly.Tests/Mapping/SpecialTypeTest.cs

Closes https://github.com/riok/mapperly/issues/438
Closes https://github.com/riok/mapperly/issues/437

feat: directly assign System.Uri and System.Version when deep cloning

---

Riok.Mapperly.sln
benchmarks/Riok.Mapperly.Benchmarks/MappingBenchmarks.cs
benchmarks/Riok.Mapperly.Benchmarks/Program.cs
benchmarks/Riok.Mapperly.Benchmarks/Riok.Mapperly.Benchmarks.csproj
benchmarks/Riok.Mapperly.Benchmarks/SourceGeneratorBenchmarks.cs
test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs

Adapted code from [Mediator](https://github.com/martinothamar/Mediator/tree/main/benchmarks/Mediator.Benchmarks/SourceGenerator) to benchmark Mapperly source generator performance. This benchmark uses the sample project although a different more complex file could be used instead.

feat: added source generator benchmark

---

src/Riok.Mapperly/Helpers/EnumerableExtensions.cs

Use simpler `IEnumerable<T>` to `HashSet<T>` constructor

fix: use simple HashSet constructor

---

src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs
src/Riok.Mapperly/Configuration/EnumConfiguration.cs
src/Riok.Mapperly/Configuration/MapperConfiguration.cs
src/Riok.Mapperly/Configuration/PropertiesMappingConfiguration.cs
src/Riok.Mapperly/Configuration/PropertyMappingConfiguration.cs
src/Riok.Mapperly/Configuration/StringMemberPath.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IMembersBuilderContext.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs

chore: attribute data accessor should resolve arguments based on target type

---

src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfo.cs
src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs
src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/EnumerableMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/MemoryMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/SpanMappingBuilder.cs

Refactor the collection info to include the type information and count property name to make several assertions easier.

chore: refactor collection info

---

.github/linters/.markdown-lint.yml
docs/docs/getting-started/faq.md
docs/docusaurus.config.js
docs/package-lock.json
docs/package.json
docs/src/plugins/rehype/rehype-faq/index.js
docs/src/plugins/rehype/rehype-faq/package.json

Adds an faq page to the docs with structured data to improve SEO.
Fixes #441

docs: frequently asked questions

---

.github/workflows/docs.yml
docs/.gitignore
docs/docusaurus.config.js
docs/prebuild.ts
docs/static/robots.txt

Disallow robots on the next docs preview page.

docs: next docs disallow robots

---

.github/workflows/test.yml

Run tests on main to get accurate test coverage results in the pul requests.

chore: run tests on main to get accurate coverage results

---

docs/docs/contributing/debugging.md
src/Riok.Mapperly/Properties/launchSettings.json

chore: add debug launch profile

---

.editorconfig
src/Directory.Build.props
src/Riok.Mapperly/BannedSymbols.txt
src/Riok.Mapperly/Descriptors/Enumerables/CollectionInfoBuilder.cs
src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityBuilder.cs
src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityInfo.cs
src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityMember.cs
src/Riok.Mapperly/Descriptors/Enumerables/EnsureCapacity/EnsureCapacityNonEnumerated.cs
src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachAddEnumerableExistingTargetMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/ForEachSetDictionaryExistingTargetMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/ForEachAddEnumerableMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/ForEachSetDictionaryMapping.cs
src/Riok.Mapperly/Descriptors/SymbolAccessor.cs
src/Riok.Mapperly/Emit/ReferenceHandlingSyntaxFactoryHelper.cs
src/Riok.Mapperly/Emit/SyntaxFactoryHelper.cs
src/Riok.Mapperly/Helpers/SymbolExtensions.cs
src/Riok.Mapperly/Helpers/UniqueNameBuilder.cs
src/Riok.Mapperly/MapperNode.cs
src/Riok.Mapperly/Riok.Mapperly.csproj

Add Meziantou.Analyzer and BannedApiAnalyzers to enforce code style / quality.

chore: add Meziantou.Analyzer and BannedApiAnalyzers

---

.github/workflows/benchmark.yml
.github/workflows/test.yml
.gitignore
benchmarks/Riok.Mapperly.Benchmarks/MappingBenchmarks.cs
benchmarks/Riok.Mapperly.Benchmarks/SourceGeneratorBenchmarks.cs

Replaces https://github.com/riok/mapperly/pull/504

chore: add benchmark action

---

.github/workflows/benchmark.yml

Increase the performance threshold due to flaky results of the GH runner.

chore: increase performance threshold

---

.github/workflows/test.yml
test/Riok.Mapperly.IntegrationTests/Helpers/Versions.cs
test/Riok.Mapperly.IntegrationTests/ProjectionMapperTest.cs
test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj
test/Riok.Mapperly.IntegrationTests/_snapshots/ProjectionMapperTest.ProjectionShouldTranslateToQuery_NET8_0.verified.sql

Runs the integration tests with .NET 8.0 preview

chore: run integration tests with .NET 8.0

---

docs/docs/getting-started/installation.mdx
docs/docs/intro.md
docs/docusaurus.config.js
docs/src/components/Conditional.tsx
docs/src/components/HomepageFeatures/index.tsx
docs/src/components/NavbarItems/VersionsNavbarItem/index.tsx
docs/src/components/NavbarItems/VersionsNavbarItem/styles.module.css
docs/src/custom-fields.ts
docs/src/theme/NavbarItem/ComponentTypes.js

Adds a version switcher dropdown in the nav bar with the current next and stable version.

docs: add version dropdown with the current next and stable version

---

benchmarks/Riok.Mapperly.Benchmarks/SourceGeneratorBenchmarks.cs
src/Riok.Mapperly/Configuration/MapperConfiguration.cs
src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs
src/Riok.Mapperly/Descriptors/Mappings/NewValueTupleConstructorMapping.cs

chore: Code cleanup

---

src/Riok.Mapperly/Descriptors/SymbolAccessor.cs

This change aims to reduce the number of allocations for cases where a valid source member does not exist. Ordinary usage should receive a very minor performance boost.
- `TryFindMemberPath` passes the same `List<IMappableMember>` to `TryFindPath`, clearing it after failure. 
- No longer use the `Count` of the path to determine when a valid path has been found. Instead `TryFindPath` returns true if the path has fully iterated.
- Used to call `ToList` on the path in order to calculate its length. This would cause an enumeration creating new strings and a `List<string>` allocation. Most of the substrings would never be used if a previous member is not found.
- Only creates a new `MemberPath` after ignore source is checked.
Allocations for a target member with `n` capital letters and no …

feat: refactor `TryFindMemberPath` preventing unneeded `List` & `string` allocations

---

src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs

Uses `WellKnownTypes` to check if `UnsafeAccessorAttribute` is available. 
Could remove `ROSLYN4_7_OR_GREATER` as it isn't really needed.
Fixes #845

feat: improve `UnsafeAccessor` version check

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs

fix: obsolete constructors should have the last priority whlie matching constructors (regression)

---

Directory.Build.props
docs/prebuild.ts
test/Riok.Mapperly.IntegrationTests/BaseMapperTest.cs
test/Riok.Mapperly.IntegrationTests/Riok.Mapperly.IntegrationTests.csproj

Use the new simplified .NET 8.0 artifacts output

chore: use simplified artifacts output

---

src/Riok.Mapperly/Descriptors/DescriptorBuilder.cs
src/Riok.Mapperly/Descriptors/SimpleMappingBuilderContext.cs
src/Riok.Mapperly/Diagnostics/DiagnosticCollection.cs
src/Riok.Mapperly/MapperGenerator.cs

Create a diagnostic collection class to simplify the code to report diagnostics.

chore: diagnostics refactoring

---

src/Riok.Mapperly/Descriptors/MappingBuilders/CtorMappingBuilder.cs
test/Riok.Mapperly.Tests/Mapping/CtorTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyConstructorResolverTest.cs

fix: when resolving constructors allow a non-nullable value type to be assigned to a nullable value type

---

docs/docs/configuration/existing-target.md

Rel. https://github.com/riok/mapperly/discussions/989

docs: improve merge objects documentation

---

docs/docs/configuration/derived-type-mapping.md

Fixed typos in derived-type-mapping.md.
Fixes # n/a

chore: fix typos in derived-type-mapping.md

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewValueTupleMappingBodyBuilder.cs
src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/ConstructorParameterMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/MemberMappings/ValueTupleConstructorParameterMapping.cs
src/Riok.Mapperly/Descriptors/TypeMappingKey.cs
test/Riok.Mapperly.Tests/Mapping/UseMapperTest.cs

Fixes https://github.com/riok/mapperly/pull/1029/files/0a2b80480a5fe55e06218fe5d0d5d7b8ba014f39#r1443806308
Fixes https://github.com/riok/mapperly/issues/1050

fix: upgrade parameter nullability correctly

---

docs/docs/configuration/existing-target.md

* Navigate to the [Existing target](https://mapperly.riok.app/docs/configuration/existing-target/) page;
* Locate `null value handling` link on the bottom with the localhost address.

docs: Updated link to localhost with relative path

---

src/Riok.Mapperly/Configuration/MapperConfiguration.cs
test/Riok.Mapperly.Tests/Helpers/MapperConfigurationBuilderTest.cs

Reflection based configuration merger test to not forget a property

chore: test all mapping merger configuration properties

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
test/Riok.Mapperly.Tests/Mapping/EnumerableExistingTargetTest.cs

fix: map init only collection in existing target mapping correctly

---

docs/docs/configuration/existing-target.md

docs: fix existing target merge object sample

---

.github/workflows/test.yml

Fixes the code coverage by using pull request target event for the test action instead of the pull request event.

fix code coverage comment by using pull request target event

---

test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs

Rel. https://github.com/riok/mapperly/issues/1229

chore: add required property and ctor parameter test

---

.github/workflows/test.yml

See https://github.com/danielpalme/ReportGenerator-GitHub-Action/issues/21

chore: fix ci cd pipeline

---

src/Riok.Mapperly/Descriptors/MappingBuilders/ExistingTargetMappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/MappingBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBuilders/NewInstanceObjectMemberMappingBuilder.cs
src/Riok.Mapperly/Descriptors/Mappings/NewValueTupleExpressionMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UnimplementedMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedExistingTargetMethodMapping.cs
src/Riok.Mapperly/Descriptors/Mappings/UserMappings/UserDefinedNewInstanceMethodMapping.cs
src/Riok.Mapperly/Emit/Syntax/SyntaxFactoryHelper.Exception.cs
test/Riok.Mapperly.Tests/Mapping/EnumerableTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
test/Riok.Mapperly.Tests/Mapping/ReferenceHandlingTest.cs
test/Riok.Mapperly.Tests/_snapshots/ObjectPropertyConstructorResolverTest.ClassToClassPrivateCtorShouldDiagnostic.verified.txt

fix: report inaccessible constructor instead of mapping could not be created

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/SourceValueBuilder.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueMethodTest.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyValueTest.cs

allow assignments of MapValue constant value types to nullable value types

---

docs/docs/getting-started/installation.mdx
src/Riok.Mapperly.Abstractions/MapperAttribute.cs

Fixes https://github.com/riok/mapperly/issues/1537

add hint to clarify abstractions scope runtime only works within same project

---

src/Riok.Mapperly/Symbols/Members/PropertyMember.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs

Correct analysis of property member accessors

---

src/Riok.Mapperly/Configuration/IMemberPathConfiguration.cs
src/Riok.Mapperly/Configuration/StringMemberPath.cs
src/Riok.Mapperly/Configuration/SymbolMemberPath.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/IMembersBuilderContext.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingBuilderContext.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingState.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/MembersMappingStateBuilder.cs
src/Riok.Mapperly/Descriptors/MappingBodyBuilders/ObjectMemberMappingBodyBuilder.cs
src/Riok.Mapperly/Helpers/ListDictionary.cs
src/Riok.Mapperly/Symbols/Members/MemberPath.cs
src/Riok.Mapperly/Symbols/Members/NonEmptyMemberPath.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
test/Riok.Mapperly.Tests/Mapping/ValueTupleTest.cs

allow multiple MapProperty attributes for the same target member

---

test/Riok.Mapperly.Tests/Mapping/EnumRequiredMappingTest.cs

add enum required mapping none test

---

docs/docs/configuration/queryable-projections.mdx

fix typo in docs queryable-projections.mdx

---

src/Riok.Mapperly/Descriptors/MappingBodyBuilders/NewInstanceObjectMemberMappingBodyBuilder.cs
test/Riok.Mapperly.Tests/Mapping/ObjectPropertyInitPropertyTest.cs

fix: only diagnostic missing member mappings for required init members

---

src/Riok.Mapperly/Descriptors/Mappings/ExistingTarget/NullDelegateExistingTargetMapping.cs
test/Riok.Mapperly.Tests/Mapping/EnumerableExistingTargetTest.cs

fix: add value suffix when getting non-enumerated count on nullable value types

---

docs/docs/configuration/flattening.md

docs: improve fullnameof docs
